- .gitignore
- Dockerfile
- config/custom-environment-variables.yaml
- config/default.yaml
- index.js
- package.json
- screwdriver.yaml
- test/.eslintrc.yaml
- test/index.test.js
The queue-executor should pass in some config like this:
```
executor:
name: k8s-vm
options:
kubernetes: ...
buildConfig:
apiUri:
buildId:
container:
token:
```
The worker then just takes this config and create a new Executor instance, then calls start to create a pod with the build config. 
Redis information should be available as `REDIS_HOST`, `REDIS_PORT`, and `REDIS_PORT`
Related: https://github.com/screwdriver-cd/screwdriver/issues/431
> feat: Add workers

- index.js
- lib/jobs.js
- package.json
- test/index.test.js
- test/jobs.test.js
We want to implement a `stop` functionality in the workers. Performing a refactor would make that effort much easier to achieve and isolate the changes away from parts of the module that should not be affected by it.
Refactor the `jobs` related functionality into a submodule. 
In addition, raises code coverage:
```
=============================== Coverage summary ===============================
Statements   : 96.43% ( 54/56 )
Branches     : 100% ( 6/6 )
Functions    : 88.89% ( 16/18 )
Lines        : 96.43% ( 54/56 )
================================================================================
```
```
=============================== Coverage summary ===============================
Statements   : 96.61% ( 57/59 )
Branches     : 100% ( 6/6 )
Functions    : 90% ( 18/20 )
Lines        : …
```
> fix: jobs as a dedicated submodule

- README.md
- lib/jobs.js
- test/jobs.test.js
Currently, the queue workers do not support the ability to stop a build that is already running. 
Define a `stop` job that will invoke a stop command with the related execution engine.
* Issue screwdriver-cd/screwdriver#693
> feat(693): stop jobs

- config/custom-environment-variables.yaml
- config/default.yaml
- index.js
Need to add prefix to the queue name for beta and prod environments.
We will have separate workers for beta and prod. Need different queue names so that they will listen to the right queue.
E.g. for beta-worker, it will listen to 'beta-builds'
> feat: add prefix to the queue name

- index.js
- test/index.test.js
This is the right format to consume redis password. 
[node-resque](https://github.com/taskrabbit/node-resque)'s example is lying.
> fix: fix the format for redis password

- config/redis.js
- index.js
- lib/jobs.js
- package.json
- test/index.test.js
- test/jobs.test.js
- test/redis.test.js
The executor-queue plugin puts the full build configuration into a redis database. This PR ensures that the workers will get that config from redis as the first step when processing jobs.
Merge with https://github.com/screwdriver-cd/executor-queue/pull/7
> Workers now obtain the build config from redis

- lib/jobs.js
- test/jobs.test.js
`ioredis` takes its options in a slightly different way than `node-resque`.
This pull calls the constructor in the same way as `node-resque`.
https://github.com/luin/ioredis/blob/master/lib/redis.js#L100
https://github.com/luin/ioredis/blob/master/API.md#new_Redis
> fix(redis): fix format of ioredis constructor

- lib/jobs.js
- test/jobs.test.js
* Buildconfigs are being stored in redis as strings, need to `JSON.parse` them before using
* Switch tests to use promises instead of `done` callbacks
> fix(redis): parse the buildconfig objects

- lib/jobs.js
- test/jobs.test.js
adding retry for job start and stop
Reference: https://github.com/taskrabbit/node-resque/blob/master/examples/retry.js
Blocked by: https://github.com/screwdriver-cd/executor-k8s-vm/pull/7
> feat: adding retry for job start and stop

- lib/jobs.js
- test/jobs.test.js
plugin name should be lower case
They change the plugin name to uppercase in latest release.
We are using an older version which user lowercase.
https://www.npmjs.com/package/node-resque
> fix: plugin name should be lower case

- lib/jobs.js
- test/jobs.test.js
The retryLimit is in seconds instead of miliseconds.
Their documentation didn't mentioned anything about it.
> fix: reduce the retryLimit to 5

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
We'd like to use jenkins executor via `queue-worker`, but `queue-worker` has no settings for that.
This PR adds the settings for the jenkins executor.
The original settings are [default.yaml](https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L124-L131) and [custom-environment-varialbes.yaml](https://github.com/screwdriver-cd/screwdriver/blob/master/config/custom-environment-variables.yaml#L102-L131).
And I adjust the settings like other executor settings (remove `enabled` setting from custom-environment-variables.yaml).
https://github.com/screwdriver-cd/screwdriver/issues/432
> feat(432): add jenkins-executor settings to config

- lib/jobs.js
We lost context of this for the fancy syntax.
Switch back to old way
> fix: fix syntax

- config/custom-environment-variables.yaml
- config/default.yaml
- config/redis.js
- test/jobs.test.js
- test/redis.test.js
Although the Redis server may have a TLS proxy in front of it, the clients must also be configured to communicate to it via TLS. This change allows a configuration flag to be available for cluster maintainers to enable this feature.
This feature does _NOT_ support self-signed certificates.
Allow a flag for configuring the Redis client to communicate with the Redis server via TLS.
* Executor-related change: screwdriver-cd/screwdriver#797
> feat: configuration flag for enabling Redis TLS communication

- screwdriver.yaml
Pull in new version of executor-k8s-vm and update workflow
Pulls in https://github.com/screwdriver-cd/executor-k8s-vm/pull/19
> fix: use new workflow and dependency on executor-k8s-vm

- config/custom-environment-variables.yaml
These were not added, so CPU was insufficient because it requests 2 CPU for each build.
> fix: update config for executors

- config/custom-environment-variables.yaml
It would be convenient if users could specify a URL to send executor data to their metric services.
Add an example of `metricHost` usage in `default.yaml` and read an environment variable, `ECOSYSTEM_METRIC_HOST`, in `custom-environment-variables.yaml`.
Merge for executor-k8s-vm implementation: https://github.com/screwdriver-cd/executor-k8s-vm/pull/24
> feat: Add Prometheus pushgateway environment variable

- package.json
Both the `executor-k8s-vm` and `executor-k8s` plugins have been updated to refer to an annotation for users to configure build timeouts in their pipeline. By including this update in the `queue-worker`, we can enable users access to this feature.
Update both the `executor-k8s-vm` and `executor-k8s` strategies to include the ability to use annotations for users to customize their build timeouts.
* Feature issue
* https://github.com/screwdriver-cd/screwdriver/issues/545
* `executor-k8s` PR that introduces the annotations update
* https://github.com/screwdriver-cd/executor-k8s/pull/73
* `executor-k8s-vm` PR that introduces the annotations update
* https://github.com/screwdriver-cd/executor-k8s-vm/pull/25
> feat: update executor-k8s & executor-k8s-vm strategies

- package.json
Both the `executor-k8s-vm` and `executor-k8s` plugins have been patched to refer to `build-timeout` in minutes instead of seconds.
Update both the `executor-k8s-vm` and `executor-k8s` strategies to pull in the patched Launcher interface.
* Feature issue
* https://github.com/screwdriver-cd/screwdriver/issues/545
* `executor-k8s` PR
* https://github.com/screwdriver-cd/executor-k8s/pull/75
* `executor-k8s-vm` PR
* https://github.com/screwdriver-cd/executor-k8s-vm/pull/26
> fix: build timeout measured in minutes

- config/custom-environment-variables.yaml
- config/default.yaml
`executor-k8s` does not support adding tolerations config.
This PR adds tolerations config.
Related: https://github.com/screwdriver-cd/screwdriver/issues/845
Similar Updates: 
- https://github.com/screwdriver-cd/queue-worker/pull/39
- https://github.com/screwdriver-cd/queue-worker/pull/40
> feat(845): add config for tolerations to k8s

- config/custom-environment-variables.yaml
- config/default.yaml
Add an ability to configure preferred node affinity like https://github.com/screwdriver-cd/screwdriver/issues/827.
This PR adds `preferredNodeSelectors` to be able to use `preferredDuringSchedulingIgnoredDuringExecution` config in the pod execution.
- Related: https://github.com/screwdriver-cd/screwdriver/issues/972
- Similar PR: 
- https://github.com/screwdriver-cd/queue-worker/pull/39
- https://github.com/screwdriver-cd/queue-worker/pull/40
- [Node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature)
> feat(972): add preferredNodeSelectors config to worker

- config/custom-environment-variables.yaml
We cannot set other selectors if we want to use other selectors with multiple executors (i.e. k8s and k8s-vm).
This PR fixes this problem.
Related: https://github.com/screwdriver-cd/screwdriver/issues/996.
> feat(996): rename to K8S_VM_NODE_SELECTORS for worker

- package.json
- screwdriver.yaml
Node.js 6 is slowly becoming deprecated, with popular packages such as `semantic-release` no longer supporting it.
* Change image in `screwdriver.yaml` to `node:8`
> fix(hip): Update to node:8

- config/custom-environment-variables.yaml
- config/default.yaml
Allow admin to configure default build timeout 
Related: https://github.com/screwdriver-cd/screwdriver/issues/545
> fix(545): cluster configurable build timeout

- screwdriver.yaml
switching to use toolbox
`gitversion` was changed to support `darwin` and `linux`: https://github.com/screwdriver-cd/gitversion/commit/2ce30c16614d6e305f43a1dc7c2e52068b6aafaa, so the package name is now different. 
However, in the gist, it's still trying to look for `gitversion` as the name. Therefore, builds are failing: https://cd.screwdriver.cd/pipelines/301/builds/21433
> fix: use toolbox

- package.json
Some Screwdriver dependencies have been updated to use Node.js 8 features, such as `async/await`. Since this change is breaking (`node:6` doesn't support it), these dependencies need to be updated manually.
* Update any dependencies that had a major version bump due to `node:8` upgrades
> fix(hip): Update screwdriver dependencies that use node:8

- lib/jobs.js
- test/jobs.test.js
Currently getting: 
```
Plugin must be the constructor name or an object null [object Object]
```
> fix: require blockedby correctly

- config/custom-environment-variables.yaml
- config/default.yaml
- config/redis.js
- lib/BlockedBy.js
- lib/jobs.js
- test/blockedBy.test.js
- test/jobs.test.js
- test/redis.test.js
Address the edge case described below:
- User starts A1
- User starts A2 - get blocked by itself -> reenqueue in 2 mins
- A1 finishes 
- User starts A3 - not blocked -> start A3
- 2 mins passed. A2 is enqueued -> start A2
Therefore, the events will be out of order: A1->A3->A2. This PR fixes it by having each waiting job as a list `waitingjob_jobId` with the members is the `buildId`
For example: `waiting_job_A` has `build2` (event A2) as its member. When A3/build3 comes, it will check `build3 !== build2`, so it will reenqueue. Then when A2/build2 comes, it checkes `build2 === build2`, so it will start the build. 
Also in this PR:
- Switch unit to mins instead of secs
- Allow the options to be configurable
Follow up of: https://github.com/screwdriver-cd/queue-worker/pull/60
Related: …
> fix: Make sure events are sequential, Allow blocked by options to be configurable.

- lib/BlockedBy.js
- test/blockedBy.test.js
I noticed that the plugin did not take in the plugin options and just use the default value for `reenqueueWaitTime` and `blockTimeout`.
I looked into their code here: https://github.com/taskrabbit/node-resque/blob/master/lib/pluginRunner.js#L24-L36
It looks like they construct a new plugin, then get the `pluginName`, and then use the `pluginName` to get the `pluginOptions`. However, inside their constructor, `pluginName` is hardcoded to `CustomPlugin`: https://github.com/taskrabbit/node-resque/blob/master/lib/plugin.js#L5
Very strange! I'm a little confused on how their own plugin options could work. But from the code it looks like we need to override the plugin name .
> fix: add blockedby name

- config/default.yaml
- lib/BlockedBy.js
- test/blockedBy.test.js
- test/jobs.test.js
The previous fix (https://github.com/screwdriver-cd/queue-worker/pull/64) worked! 
I'm just setting the value to default so I don't need to change it in our deployment.
> fix: decrease enqueue time

- package.json
I found that node-resque@5.3.1 does not handle redis auth properly and 5.3.0 works fine, so I pinned the version of node-resque to 5.3.0.
queue-worker@1.12.0 + node-resque@**5.3.0**
```
> screwdriver-queue-worker@1.12.0 start /usr/src/app/node_modules/screwdriver-queue-worker
> node index.js
info: *** checked for worker status: x (event loop delay: Infinityms)
info: scheduler started
info: worker[1] started
info: worker[1] polling builds
info: *** checked for worker status: + (event loop delay: 2ms)
info: worker[1] paused
info: *** checked for worker status: x (event loop delay: 1ms)
```
queue-worker@1.12.0 + node-resque@**5.3.1**
```
> screwdriver-queue-worker@1.12.0 start /usr/src/app/node_modules/screwdriver-queue-worker
> node index.js
info: *** checked for worker status: x (event …
```
> fix: node-resque@5.3.1 is broken

- lib/BlockedBy.js
- test/blockedBy.test.js
So we know exactly which build is running
> fix: set buildId as value

- lib/BlockedBy.js
- test/blockedBy.test.js
I noticed the waiting values are not always sorted. This might help with getting the correct first waiting build. It's unclear why the values are not sorted. 
```
lrange "waiting_job_14528" 0 -1
1) "136634"
2) "136730"
3) "136715"
4) "136712"
5) "136608"
6) "136644"
7) "136753"
8) "136788"
9) "136991"
```
> fix: sort waiting values

- lib/BlockedBy.js
- test/blockedBy.test.js
Flag will come in as a string because of kubernetes
> fix: use string for flag because of k8s

- lib/BlockedBy.js
- test/blockedBy.test.js
Only call `mget` when `blockedBy` is there. 
Previously, we always have `blockedBy`, but with flag turns off, this could be an empty array. And `mget` gives some issues. Seems like we need to check if the array length >0 first. 
Similar code here: https://github.com/taskrabbit/node-resque/blob/1b8509651bf5962b987cce2de819cd1d2c9576b7/lib/queue.js#L181-L183
> fix: do not call mget if not blocked

- lib/BlockedBy.js
- test/blockedBy.test.js
Technically shouldn't get to this stage if starting from fresh. 
But since `redis` might consist some leftover data, it can get to this stage.
> fix: also wrap waiting key check

- lib/BlockedBy.js
- test/blockedBy.test.js
Return `false` to not run the job when it's in the delete list.
Clean up the keys. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/1110
>  fix: Clean up jobs that were aborted while queued

- package.json
I updated the version of node-resque.
`v5.3.2` should include the fix of #68.
Ref: https://github.com/taskrabbit/node-resque/pull/246
> fix: bump node-resque version

- lib/jobs.js
- package.json
- test/jobs.test.js
Previously, we addressed this case by adding `delete` key:
- Build is still in the queue and **picked up by worker**
- User aborts
- Executor-queue adds `delete` key, and call `stop` which cleans up `waiting` key 
- Worker puts back to queue
- Worker picks up same build again, in `beforePerform`, it does clean up and will not proceed. 
There is a new edge case scenario I found:
- Build is still in the queue and **not picked up by worker**
- User aborts
- Executor-queue removes it from queue, adds the `delete` key, `waiting` key remains
- Because it's removed from queue, it will not go to `beforePerform` to clean up. `waiting` key still contains this buildId, so subsequent builds cannot be started. 
This PR moves all the clean up to worker stop. This will be called no matter what. If the …
> fix: move cleanup to worker stop

- package.json
Pull in https://github.com/screwdriver-cd/executor-k8s/pull/85
Will disable `prod` and test it in `beta` first.
> fix: pull in new executor-k8s

- package.json
with hab cache.
https://github.com/screwdriver-cd/executor-k8s-vm/releases
Related to https://github.com/screwdriver-cd/screwdriver/issues/877
> fix(877): pull in new k8s-vm [2]

- config/custom-environment-variables.yaml
- config/default.yaml
Configurations for the Jenkins Executor's PR.
Add the configurations for Jenkins build timeout.
screwdriver/executor-jenkins PR: https://github.com/screwdriver-cd/executor-jenkins/pull/22
issue: https://github.com/screwdriver-cd/screwdriver/issues/1159
> feat: Add config for Jenkins build timeout

- config/custom-environment-variables.yaml
- config/default.yaml
Allow cluster admin to inject annotations to build pod.
Related to https://github.com/screwdriver-cd/screwdriver/issues/818
> fix(818): add annotations to k8s config

- package.json
pull in new executor plugins with parse annotation function and status msg in k8s and k8s-vm if no resources available.
> fix: pull in new executor plugins

- config/custom-environment-variables.yaml
executor-k8s-vm will consume the value of `options.kubernetes.resources.disk.high` and use it to set the toleration/node affinity of pods that require a high disk resource.
Add `options.kubernetes.resources.disk.high` as a configurable option.
https://github.com/screwdriver-cd/executor-k8s-vm/pull/42
https://github.com/screwdriver-cd/screwdriver/issues/757
> feat(757): Add disk label as a configurable option

- index.js
- lib/jobs.js
- test/index.test.js
- test/jobs.test.js
this plugin object contains info about how many times already retried etc. currently it's showing like `[object Object]` since it's an object.
> fix: log plugin object

- Dockerfile.local
- config/custom-environment-variables.yaml
- config/default.yaml
- config/rabbitmq.js
- lib/Filter.js
- lib/jobs.js
- package-lock.json
- package.json
- test/filter.test.js
- test/jobs.test.js
- test/rabbitmq.test.js
- add a `scheduler` mode (instead of start the job immediately, scheduler will enqueue the job to rabbitmq based on its buildcluster)
- add a `Filter` plugin: during the transition / test period, we will have both old queue-worker and new scheduler running as 2 separate instances. Both of them are polling from the same redis. To avoid picking up wrong jobs, Filter plugin will reenqueue the job doesn't belong to the current instance back to redis.
> feat(1319): add scheduler mode 

- package.json
This PR pulls in the latest k8s-vm
- https://github.com/screwdriver-cd/executor-k8s-vm/pull/47
- https://www.npmjs.com/package/screwdriver-executor-k8s-vm
> fix: pull in latest k8s-vm

- lib/jobs.js
- package-lock.json
- package.json
- test/jobs.test.js
- switch to a different amqp library with proper connection management
https://github.com/benbria/node-amqp-connection-manager
- pass build token for stop job to rabbitmq
Related to https://github.com/screwdriver-cd/screwdriver/issues/1319
> fix: switch to a different amqp library

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/jobs.js
- test/jobs.test.js
`assertExchange` requires `config` permission which we don't want to give for the producer. Switch to use `checkExchange` instead. 
Ref: https://www.squaremobius.net/amqp.node/channel_api.html#channel_checkExchange
> fix: switch to checkExchange because of permission

- package.json
https://github.com/screwdriver-cd/executor-k8s/pull/105
Blocked by: https://github.com/screwdriver-cd/executor-k8s-vm/pull/52
> fix: pull in new executors

- config/custom-environment-variables.yaml
- make disk speed label configurable via ENV 
Related to https://github.com/screwdriver-cd/executor-k8s-vm/pull/53
> fix: add disk speed label config [3]

- lib/BlockedBy.js
- lib/helper.js
- test/blockedBy.test.js
- test/jobs.test.js
There are two major race conditions if multiple events start around the same time:
1. build0 finishes, build1 is in waiting queue and build2 comes around same time
-> build1 tries to start since it's the only one waiting
-> build2 tries to collapse build1 
this may leave build1 in a weird state, it's actually started but status is `COLLAPSE` and following builds will be blocked by it.
To solve this problem, add a check for `this.queueObject.connection.redis.lrem(waitingKey, 0, bId)`, whoever pops the build from the waitingQueue will proceed, otherwise return.
2. build1, build3 got picked up by worker first and build2 got picked up by worker later
-> build3 collapses build1 and starts after build0 finishes
-> build3 finishes, build2 will try to start since it's the only build waiting
To …
> fix(1482): fix race conditions for collapse

- config/custom-environment-variables.yaml
- config/default.yaml
- lib/BlockedBy.js
- package.json
- test/blockedBy.test.js
- turn collapse feature flag into default behavior
- this way, cluster admin can decide if they want to opt in or opt out for `collapse` 
`Related to`: https://github.com/screwdriver-cd/screwdriver/issues/1482
> fix(1482): turn collapse feature flag into default behavior

- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
pull in new executor-k8s-vm with custom cpu and ram: https://github.com/screwdriver-cd/executor-k8s-vm/pull/55
> fix: pull in new executor-k8s-vm with custom cpu and ram

- lib/BlockedBy.js
- package.json
- test/blockedBy.test.js
We have a default block timeout of 2 hours to expire the running key to clean up things if the build doesn't end properly. But this will break builds that has a custom timeout of more than 2 hours. Key will be expired and next build will run even though the previous one is still running.
This PR will set block timeout based on build timeout with some buffer.
> fix: set block timeout based on build timeout

- package.json
when deploying this as a worker, please make sure pulling in hyperctl-image `1.0.6` together as K8S_BASE_IMAGE.
https://github.com/screwdriver-cd/hyperctl-image/pull/28
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1489
> fix: pull in latest executor-k8s-vm

- config/custom-environment-variables.yaml
- config/default.yaml
[An error message](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L407-L409
) was not shown on UI and a build status was not changed even if users use invalid image.
This might be caused by pod's waiting reason is `PodInitializing` after [these retrying](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L391-L400).
To prevent this problem, `MAXATTEMPTS` and `RETRYDELAY` should be configurable.
https://github.com/screwdriver-cd/screwdriver/issues/1678
> fix(1678): [1] add configurable retryDelay and maxAttempts

- config/custom-environment-variables.yaml
Make disk space config more generic. 
This PR renames the disk space config from `high` to `space`.
Related to https://github.com/screwdriver-cd/executor-k8s-vm/pull/60
> fix: Rename disk space config

- lib/Filter.js
- test/filter.test.js
I found that there are thousands of failed "stop" job in my build queue (resque). It is caused by a TypeError on this line.
https://github.com/screwdriver-cd/queue-worker/blob/master/lib/Filter.js#L40
```
Cannot read property 'buildClusterName' of null
at Filter.beforePerform (/usr/src/app/node_modules/screwdriver-queue-worker/lib/Filter.js:40:25)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```
The root cause seems to get nonexistent buildConfig from redis after its pipeline is deleted.
* Check if the existent of buildConfig and abort the processing if it is empty.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this …
> fix: fix runtime error when pipeline is gone

- config/custom-environment-variables.yaml
- config/default.yaml
- index.js
- test/index.test.js
In my environment, many builds usually run at the same time.
Current worker watches pods until they are created, so this process fills up worker slots. And the number of workers is 10 (hardcoded).
I made MultiWorker option configurable so that users can scale their worker count via maxTaskProcessors.
Plus, I removed unused config `toDisconnectProcessors`.
https://github.com/taskrabbit/node-resque/commit/1e2be968813ff1f82234f37a4ce8ed97505b3e18
> fix: Make worker option customizable

- package.json
`queue-worker` ought to be using the latest version of `screwdriver-executor-docker` v4 this case.
This fix `queue-worker` to use `screwdriver-executor-docker` v4
Screenshot:
> fix: upgrade screwdriver-executor-docker to v4 in package.json

- lib/BlockedBy.js
- package.json
- test/blockedBy.test.js
Due to api slowness and retry logic sometimes multiple builds from the same event gets triggered irrespective of the build status. This causes downline jobs to get triggered multiple times.
This PR will add a check to prevent builds triggered from the same eventId to not be re-enqueued
> fix: Prevent re-enqueue of builds from same event

- index.js
- lib/timeout.js
- test/index.test.js
- test/timeout.test.js
Build time out which is enforced via launcher doesn't work on scenarios when build container crashes. This is because it relies on launcher process to be running to enforce the time out.
This PR checks whether the time build has spent being processed is greater than the timeout of the build and updates the status to FAILURE. This fixes the case when container has crashed but the build shows still running with no way stop without manual intervention.
https://github.com/screwdriver-cd/screwdriver/issues/1839
Other related PR's, add property to schema and buildConfig
https://github.com/screwdriver-cd/data-schema/pull/371
https://github.com/screwdriver-cd/executor-queue/pull/77
I confirm that this contribution is made under the terms of the license found in the root directory of this …
> fix(1839): Add timeout check to worker
