screwdriver-cd/queue-worker

index.js, test/index.test.js
This change was not updated in the previous PR
=> fix: call winston info

index.js, test/index.test.js
For updating build status, it should be `PUT` instead of `POST`:
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/update.js#L9
=> fix: change request method to PUT

index.js, test/index.test.js
- end workers before process.exit
- re-order tests
=> fix: end workers before process.exit

package.json
=> fix: pull in new k8s-vm plugin

index.js, test/index.test.js
Scheduler is needed for Retry plugin.
This PR will add scheduler and end it before the process ends.
Docs for node-resque 4.X, it's on v4 branch: https://github.com/taskrabbit/node-resque/tree/v4
=> fix: add scheduler for retry

index.js, lib/jobs.js, test/index.test.js, test/jobs.test.js
- remove `hdel` from start job otherwise when it retries there is no build config.
- fix updateBuildStatus to get apiUri and token from the `fullBuildConfig`
=> fix: remove hdel from start job

config/default.yaml
Pulls in hyperctl image and executor-k8s-vm changes 
https://github.com/screwdriver-cd/hyperctl-image/pull/11
https://github.com/screwdriver-cd/executor-k8s-vm/pull/14
Original issues: https://github.com/screwdriver-cd/screwdriver/issues/758, https://github.com/screwdriver-cd/screwdriver/issues/759
=> fix: Fix comment

config/default.yaml
Setting defaults for https://github.com/screwdriver-cd/queue-worker/blob/master/config/custom-environment-variables.yaml
=> fix: update default values

README.md
https://github.com/screwdriver-cd/launcher/pull/138
=> fix: Pull in SD_STORE changes

package.json
https://github.com/screwdriver-cd/executor-k8s-vm/commit/80fd566f894a1d1c9ce0c26faef784b34c9c74b2
=> fix: Update executor-k8s-vm

README.md
=> fix: update READ for start/stop

lib/helper.js
This is getting `400` for some reason... Tested on API and it looks fine. So going to try to log this and see what's going on.
=> fix: log the request

lib/helper.js
Was added for debugging purpose. Should be removed now.
=> fix: remove logging

lib/BlockedBy.js, test/blockedBy.test.js
Related: https://github.com/screwdriver-cd/screwdriver/issues/1143
=> fix: allow retry to proceed

package.json
pull in: https://github.com/screwdriver-cd/executor-k8s-vm/pull/36
=> fix: pull in latest k8s-vm

package.json
fix for this issue https://github.com/screwdriver-cd/screwdriver/issues/1261
=> fix(1261): k8s pod delete immediately

.gitignore, config/custom-environment-variables.yaml, config/default.yaml
Add a feature flag for docker in docker.
=> feat: Adding a docker feature enabled option in k8s configuration

config/custom-environment-variables.yaml, config/default.yaml, package.json
Related to https://github.com/screwdriver-cd/screwdriver/issues/1555
=> feat(1555): Add SD_UI_URL by pulling in latest executor-k8s-vm

package.json
Up executor-k8s-vm version
[1830]
=> fix(1830): up k8s-vm version

lib/timeout.js
Review comments on PR https://github.com/screwdriver-cd/queue-worker/pull/149
Minor refactor null check
=> Minor refactor
